from collections import Counter
from django.shortcuts import render, get_object_or_404
from django.core.files.storage import FileSystemStorage
from .ml_model.predict import predict_blood_group
from .models import Prediction
from django.db.models import Q
from reportlab.pdfgen import canvas
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.core.files.base import ContentFile
import cv2
import numpy as np
import tensorflow as tf 
import os
import base64
from django.conf import settings

@login_required
def upload(request):

    if request.method == "POST":

        name = request.POST.get("name")
        dob = request.POST.get("dob")
        mobile = request.POST.get("mobile")

        captured_image = request.POST.get("captured_image")

        if captured_image:

            format, imgstr = captured_image.split(';base64,')
            ext = format.split('/')[-1]

            image_file = ContentFile(base64.b64decode(imgstr), name='scan.' + ext)

        else:

            image_file = request.FILES['fingerprint']


        file_path = os.path.join(settings.MEDIA_ROOT, "temp.png")

        with open(file_path,'wb+') as f:
            for chunk in image_file.chunks():
                f.write(chunk)


        result, confidence, top3 = predict_blood_group(file_path)

        Prediction.objects.create(

            name=name,
            dob=dob,
            mobile=mobile,
            fingerprint=image_file,
            predicted_group=result,
            confidence=confidence

        )

        return render(request,"result.html",{

            "name":name,
            "dob":dob,
            "mobile":mobile,
            "result":result,
            "confidence":round(confidence,2)

        })

    return render(request,"upload.html")

def dashboard(request):

    query = request.GET.get('q')

    if query:
        predictions = Prediction.objects.filter(
            Q(name__icontains=query) |
            Q(mobile__icontains=query) |
            Q(predicted_group__icontains=query)
        ).order_by('-created_at')
    else:
        predictions = Prediction.objects.all().order_by('-created_at')

    blood_groups = [p.predicted_group for p in predictions]

    counts = Counter(blood_groups)

    labels = list(counts.keys())
    values = list(counts.values())

    context = {
        "predictions": predictions,
        "labels": labels,
        "counts": values,
        "query": query,
        "total_patients": len(predictions),
        "O_pos": counts.get('O+',0),
        "A_pos": counts.get('A+',0),
        "B_pos": counts.get('B+',0),
        "AB_pos": counts.get('AB+',0)
    }

    return render(request,"dashboard.html",context)



def download_report(request,name,dob,mobile,result,confidence):

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="patient_report.pdf"'

    p = canvas.Canvas(response)

    p.setFont("Helvetica",14)
    p.drawString(100,800,"AI Blood Group Prediction Report")

    p.setFont("Helvetica",12)

    p.drawString(100,750,f"Patient Name: {name}")
    p.drawString(100,720,f"DOB: {dob}")
    p.drawString(100,690,f"Mobile: {mobile}")

    p.drawString(100,650,f"Predicted Blood Group: {result}")
    p.drawString(100,620,f"Confidence: {confidence}%")

    p.drawString(100,580,"Generated by AI Fingerprint System")

    p.save()

    return response    
@login_required
def patient_detail(request, id):

    patient = get_object_or_404(Prediction, id=id)

    context = {
        "patient": patient
    }

    return render(request, "patient_detail.html", context)


def delete_prediction(request, id):

    prediction = Prediction.objects.get(id=id)
    prediction.delete()

    return redirect('dashboard')